### PR TITLE
fix(QS Dashboard): fix inverted x y axis

### LINKED ISSUE #216: [bug] QS Dashboard graph x and y axis are swaped.
@sbancal It seems the x and y-axis values are swaped. could you fix it ?

image

_Originally posted by @vsdharun in https://github.com/EPFL-ENAC/CCFatiguePlatform/issues/172#issuecomment-1337523427_

### PR DESCRIPTION
**Pull request by sbancal**
FIX #216

### CODE REVIEW

File: frontend/src/views/TestsDashboard.vue [hunk 1]
```diff
@@ -327,10 +327,10 @@ export default {
         type: "line",
         name: `${testId}`,
         data: zip(
-          this.loadOption ? this.loadData[testId][this.loadOption] : [],
           this.displacementOption
             ? this.displacementData[testId][this.displacementOption]
-            : []
+            : [],
+          this.loadOption ? this.loadData[testId][this.loadOption] : []
```
Comment (guilbep) [inline frontend/src/views/TestsDashboard.vue:333]: Isn'it more readable to write: `this.loadData?.[testId][this.loadOption] ?? [];`
