### PR TITLE
fix(frontend analysis): plot cld groupby cycles

### LINKED ISSUE #225: [Feature] Frontend analysis CLD graph
- plots each lines separately

### PR DESCRIPTION
**Pull request by nicdub**
FIX #225

I used groupBy from lodash, maybe there is a simpler way of doing it.

### CODE REVIEW

File: frontend/src/components/analysis/CldAnalysis.vue [hunk 1]
```diff
@@ -128,16 +129,16 @@ export default {
...
-                name: this.method,
-                data: results.data.map((item) => [
-                  item.stress_mean,
-                  item.stress_amplitude,
-                ]),
-              },
-            ];
+            this.series = Object.entries(
+              groupBy(results.data, (row) => row.cycles_to_failure)
+            ).flatMap((cycles_to_failure) => ({
```
Comment (blueur) [inline frontend/src/components/analysis/CldAnalysis.vue:134]: .map instead of .flatMap ?

**Review by blueur — APPROVED** [review]
